# Site settings
title: Astro-w-Hack
SEOTitle: Chaoli Zhang | Homepage
header-img: img/Home-bg-Pokemon.jpg
email: c.jack.zhang@gmail.com
description: "Happy Coding"
keyword: "astro, chaoli, chaolizhang, luojilab, 认知迭代, 罗辑思维"
url: "chaolizhang.org"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Chaoli-Zhang/Chaoli-Zhang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Hello! I am Chaoli Zhang, currently a Ph.D. student
(in astrophysics) at Max Planck Institute for Radio Astronomy (MPIfR) and University
of Bonn, Germany. "
sidebar-avatar: img/Profile-Sidebar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
facebook_username:     chaoli.zhang
github_username:       chaoli-zhang
linkedin_username:    chaoli-zhang-88335a9b
jianshu_username:     e092e7c72058
# weichat_username:     chaolizhang
# twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
disqus_username: chaolizhang



# Analytics settings

# Google Analytics
ga_track_id: 'UA-105234179-1'            # Format: UA-xxxxxx-xx
ga_domain: chaolizhang.org





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


friends: [
    {
        title: " Luly and Syrtis",
        href: "http://luly.lamost.org/blog/"
    }
]

